[settings]
font_path = "assets/Roboto-Black.ttf"
renderer = "gif"
masking_frames = 0
content_path = "rsvp/document.rsvp"

[settings.video]
width = 1020
height = 720
fps = 50.0
scale = 100.0
easing = "linear"

[settings.gif]
width = 720
height = 480
fps = 50.0
scale = 90.0
easing = "linear"

[spiral]
branches = 6.0
curvature = 0.10
smoothness = 0.2
lighter_color = 0.0
darker_color = 60.0
speed = 2.0
shrink_height = 3.0
clockwise = false
color_slow = [0.0, 0.0, 0.0]
color_fast = [210.0, 10.0, 10.0]
wpm_min = 100.0
wpm_max = 600.0
tint_strength = 0.0              # 0.0 = pure greyscale, 1.0 = full tint color
